### PR TITLE
update to README

### LINKED ISSUE #3: Create comprehensive readME file

### PR DESCRIPTION
**Pull request by VeraTs**
With summary of project purpose and features, the technologies (to be) used, and members of the team. 
related issue: #3

### CODE REVIEW

**Review by lmilbaum — APPROVED** [review]
LGTM

**Review by ellaml — APPROVED** [review]
Looks great!

**Comment by oriAdler** [comment]
LGTM

**Review by oriAdler — APPROVED** [review]
LGTM

**Pull request merged**
