### PR TITLE
Add Review data model class

### LINKED ISSUE #16: Adding Review data model class
- Add Review data model class
- Add Migration files for initializing the data model

### PR DESCRIPTION
**Pull request by oriAdler**
- Modify models.py to add Review class
User and Course empty classes were added because the Review class
addresses them as foreign keys
- Add 0001_initial.py to create database migrations

Note: file 0001_initial.py had been auto-generated
Resolves: #16

### CODE REVIEW

**Comment by lmilbaum** [comment]
Wait for the CI to be green before requesting a review

**Review by lmilbaum — APPROVED** [review]
LGTM

**Comment by lmilbaum** [comment]
Anyone else want to review before I merge the PR?

**Review by ellaml — APPROVED** [review]
Looks good

**Pull request merged**
