### PR TITLE
Design the Add Review Search page

### LINKED ISSUE #119: Design the Add Review Search page

### PR DESCRIPTION
**Pull request by oriAdler**
1. Add **add_review_search.css**
  2. Modify **add_review_search.html**

Resolves: #119

### CODE REVIEW

**Comment by oriAdler** [comment]
Preview:
image

**Comment by ellaml** [comment]
Looks awesome! :)
The CSS file requires some indentation fix though

**Comment by LeonRabinovich** [comment]
The design looks very good !
I agree with Ella about the CSS file indentation ( I recommend using an auto-formatter such as prettier)

**Review by ellaml — APPROVED** [review]

**Comment by oriAdler** [comment]
@ellaml @LeonRabinovich indentation fixed

**Review by LeonRabinovich — APPROVED** [review]

**Review by VeraTs — APPROVED** [review]
Looks Great!

**Review by kobihk — APPROVED** [review]

**Pull request merged**
