### PR TITLE
Create the website with Django

### LINKED ISSUE #5: Create a "Clean" Django website for ClassRater
*Our application will be using the Django framework, so we need to make sure it is installed on our VM before accessing the website. (and pipenv should also be installed on the VM - before Django)

### PR DESCRIPTION
**Pull request by LeonRabinovich**
fix #5
We need to create a website for our application using Django.
For this we need:
1. The website folder (ClassRater)
2. The manage.py script to interact with Django

### CODE REVIEW

**Review by lmilbaum — CHANGES_REQUESTED** [review]
Is there a need for two commits? If not, squash them

**Comment by LeonRabinovich** [comment]
> 
> 
> Is there a need for two commits? If not, squash them

i squashed the commits into a single commit

**Review by lmilbaum — APPROVED** [review]
LGTM

**Review by ellaml — APPROVED** [review]

**Review by oriAdler — APPROVED** [review]
LGTM

**Pull request merged**
