### PR TITLE
Adding the Course Model

### LINKED ISSUE #18: Create Course Model and Migrations

### PR DESCRIPTION
**Pull request by VeraTs**
Added a Curse Model according to the DB ERD, and manually added to the migrations 0001_initial file.

Currently contains the fields:
- id
- name
- mandatory
- credit_points
- syllabi (is supposed to be a link in the future, for now placeholder String type)
- avg_rating
- avg_load
- num_of_raters (number of raters)
- num_of_reviewers (number of reviewers)

close #18

### CODE REVIEW

**Review by ellaml — APPROVED** [review]

**Review by oriAdler — COMMENTED** [review]
Looks good! 
Maybe the mandatory field can be BooleanField?

**Comment by VeraTs** [comment]
If I made it Boolean it would work for django, but be relegated to NUMERIC affinity in SQLite, which is a bit ambiguous to my tastes, so I went with smallInt.
(because BOOLEAN would be a NUMERIC affinity but converted to INTEGER if i use Boolean. In that case I though making it an integer from the get go is better)

**Review by oriAdler — APPROVED** [review]
LGTM

**Review by lmilbaum — CHANGES_REQUESTED** [review]
Issue is not linked

**Comment by VeraTs** [comment]
linked to issue!

**Review by lmilbaum — APPROVED** [review]

**Pull request merged**
