### PR TITLE
Fix duplicate images bug

### LINKED ISSUE #92: Fix duplicate images bug
A new **new_test_image.jpg** is created every time 
the command ```migrate``` **0006_review_test_data.py** is run

### PR DESCRIPTION
**Pull request by oriAdler**
Modify **0006_review_test_data.py** to prevent the creation
of a new image every time the function ```test_model_review_list``` test
in file **tests.py** is executed

Add **new_test_image.jpg** to prevent the creation of the image
on ```migrate``` **0006_review_test_data.py**

fix: #92

### CODE REVIEW

**Comment by oriAdler** [comment]
@VeraTs @ellaml @LeonRabinovich As GitHub runs the tests only once, to be on the safe side, I'll appreciate it if one of you can double-check me on his local repo

**Comment by LeonRabinovich** [comment]
The issue is mostly fixed, however on the first time you run `pipenv run pytest` it will create a new image which is not in our repository(and also not in this PR) -  "new_test_image.jpg" 
Running the command again will not create more test images other than the first one. 

**Just to make myself extra clear:**
Currently under ..\ClassRater\homepage\media\images we have 2 images :
1. histogram.png
2. test_image.jpg

When running pytest with the updated migration file from this PR, a 3rd image is created - new_test_image.jpg

**Review by LeonRabinovich — CHANGES_REQUESTED** [review]
The issue is mostly fixed, however on the first time you run `pipenv run pytest` it will create a new image which is not in our repository (and also not in this PR) -  **"new_test_image.jpg"** 
Running the command again will not create more test images other than the first one. 

**Just to make myself extra clear:**
Currently under ..\ClassRater\homepage\media\images we have 2 images :
1. histogram.png
2. test_image.jpg

When running pytest with the updated migration file from this PR, a 3rd image is created - **new_test_image.jpg**


I suggest to either **change the code to detect "test_image.jpg"**(image number 2),
or add "new_test_image.jpg" to the PR (if there is an actual need for it which I assume there isn't)

**Comment by oriAdler** [comment]
@LeonRabinovich If you look closely, the **new_test_image.jpg** was already added to this PR

**Comment by LeonRabinovich** [comment]
> @LeonRabinovich If you look closely, the **new_test_image.jpg** was already added to this PR

My bad :)

**Review by LeonRabinovich — APPROVED** [review]

**Review by VeraTs — APPROVED** [review]

**Review by kobihk — APPROVED** [review]

**Pull request merged**
