### PR TITLE
Design the Post Review page

### LINKED ISSUE #121: Design the Post Review page

### PR DESCRIPTION
**Pull request by oriAdler**
1. Modify **forms.py** to add bootstrap attributes
  2. Add crispy form to **add_review.html**

Resolves: #121

### CODE REVIEW

**Comment by oriAdler** [comment]
Preview:
image

**Comment by ellaml** [comment]
Nice :)
I'm gonna try to improve it a little bit in the weekend (no offence😆)
But in case I won't make it maybe it's better to at least put it in the center of the page and change the post button to have a nicer color. I know some of the things in the UX template are irrelevant but you can use the colors/font from there if you want (in the UX folder in our drive)

**Comment by LeonRabinovich** [comment]
I'm not a UX person, but I agree with Ella, I think those changes will make the page look better 
Anyways, it still looks good - so whatever you guys decide to do

**Review by LeonRabinovich — APPROVED** [review]

**Comment by oriAdler** [comment]
After Ella made some changes we can all agree this page looks much better:
image
Thank you @ellaml for your help:)

**Review by VeraTs — APPROVED** [review]
Looks Great!

**Review by ellaml — APPROVED** [review]

**Review by kobihk — APPROVED** [review]

**Pull request merged**
